### ISSUE TITLE
Fabrizio | Lesson 2

### ISSUE THREAD

**Issue by martin5211** [martin5211/learn-node-js#15]
- The dependencies imported with require always should be added into the package.json using `--save-dev` option so it can be installed using simply `npm install`.

- It's bad practice to use exports inside an Express request. Please remove it and avoid to use that in the future.

- Error: Cannot find module './file_system'

**Comment by martin5211** [comment]
Looks good. Closing issue.
